# api/config/serializer/genre.yaml
App\Entity\Genre:
  attributes:
#    id:
#      groups: ['productionGet','genreCollection','genre']
    name:
      groups: ['productionGet','genreCollection','genre']
    productions:
      groups: ['genre']
