App\Entity\Genre:
  attributes:
    id:
      groups: ['productionGet','genreCollection','genre']
    name:
      groups: ['productionGet','genreCollection','genreGet', 'genreCreate']
    productions:
      groups: ['genreGet']
