App\Entity\Production:
  attributes:
#    id:
#      groups: ['studioGet','productionGet', 'genre']
    uuid:
      groups: ['productionGet']
    title:
      groups: ['studioGet', 'productionWrite', 'genre', 'productionGet']
    description:
      groups: ['productionGet', 'productionWrite']
    studio:
      groups: [ 'productionGet', 'productionWrite']
    episodes:
      groups: [ 'productionGet', 'productionWrite']
    currentEpisodes:
      groups: [ 'productionGet', 'productionWrite']
    trailerLink:
      groups: [ 'productionGet', 'productionWrite']
    genres:
      groups: ['productionGet', 'productionWrite']
    createdBy:
      groups: ['productionGet']
    created:
      groups: ['productionGet']
