App\Entity\Studio:
  attributes:
#    id:
#      groups: ['studioGet', 'productionGet', 'studioCollection' ]
    uuid:
      groups: ['studioGet', 'studioCollection', 'productionGet', 'studioCreate']
    name:
      groups: ['studioGet', 'productionGet', 'studioCreate', 'productionWrite', 'studioCollection' ]
    productions:
      groups: ['studioGet']