# api/config/serializer/studio.yaml
App\Entity\Studio:
  attributes:
    id:
      groups: ['studioGet', 'productionGet', 'studioCollection' ]
    name:
      groups: ['studioGet', 'productionGet', 'studioWrite', 'productionWrite', 'studioCollection' ]
    productions:
      groups: ['studioGet']