hwi_oauth:
    # https://github.com/hwi/HWIOAuthBundle/blob/master/docs/2-configuring_resource_owners.md
    resource_owners:
        google:
            type:                google
            client_id:           ''
            client_secret:       ''
            scope:               "email"
            csrf: true
