hwi_oauth:
    firewall_names: [main]
    resource_owners:
        google:
            type: google
            client_id:           '%env(GOOGLE_CLIENT_ID)%'
            client_secret:       '%env(GOOGLE_CLIENT_SECRET)%'
            scope:               "email profile"
#            csrf: true
        twitter:
            type: twitter
            client_id: '%env(TWITTER_CLIENT_ID)%'
            client_secret: '%env(TWITTER_CLIENT_SECRET)%'
            csrf: true
