resources:
    App\Entity\Genre:
        shortName: 'Genre'
        description: 'Gatunek produkcji'
        normalizationContext:
            groups: [ 'genreCollection' ]
        operations:
            ApiPlatform\Metadata\GetCollection: ~
            ApiPlatform\Metadata\Get:
                normalizationContext:
                    groups: [ 'genreGet' ]
            ApiPlatform\Metadata\Post:
                denormalizationContext:
                    groups: [ 'genreCreate' ]
            ApiPlatform\Metadata\Patch: ~
            ApiPlatform\Metadata\Delete: ~


