resources:
    App\Entity\Genre:
        shortName: 'Genre'
        description: 'Gatunek produkcji'
        normalizationContext:
            groups: [ 'genreCollection' ]
        operations:
            ApiPlatform\Metadata\GetCollection: ~
            ApiPlatform\Metadata\Get:
                normalizationContext:
                    groups: [ 'genre' ]


