# api/config/api_platform/productions.yaml
resources:
  App\Entity\Production:
    shortName: 'Production'
    description: 'Film/Serial'
    normalizationContext:
      groups: [ 'productionGet' ]
#    denormalizationContext:
#      groups: [ 'productionWrite' ]
    operations:
      ApiPlatform\Metadata\GetCollection: ~
      ApiPlatform\Metadata\Get: ~
      ApiPlatform\Metadata\Post: ~
      ApiPlatform\Metadata\Patch: ~
      ApiPlatform\Metadata\Delete: ~
#        paginationItemsPerPage: 25
