resources:
  App\Entity\Production:
    shortName: 'Production'
    description: 'Film/Serial'
    normalizationContext:
      groups: [ 'productionGet' ]
#    denormalizationContext:
#      groups: [ 'productionWrite' ]
    operations:
      ApiPlatform\Metadata\GetCollection:
        filters: ['productions.search_filter', 'productions.order_filter','productions.range_filter']
      ApiPlatform\Metadata\Get: ~
      ApiPlatform\Metadata\Post: ~
      ApiPlatform\Metadata\Patch: ~
      ApiPlatform\Metadata\Delete: ~

properties:
  App\Entity\Production:
    id:
      identifier: false
    uuid:
      identifier: true