resources:
  App\Entity\Studio:
    shortName: 'Studio'
    description: 'Studio produkcji'
    denormalizationContext:
      groups: [ 'studioWrite' ]
    normalizationContext:
      groups: [ 'studioGet' ]
    operations:
      ApiPlatform\Metadata\GetCollection:
        normalizationContext:
          groups: [ 'studioCollection' ]
        filters: ['studios.search_filter']
      ApiPlatform\Metadata\Get:
        normalizationContext:
          groups: [ 'studioGet' ]
      ApiPlatform\Metadata\Post:
      ApiPlatform\Metadata\Patch: ~
      ApiPlatform\Metadata\Delete: ~

properties:
  App\Entity\Studio:
    id:
      identifier: false
    uuid:
      identifier: true

