# api/config/api_platform/studio.yaml
resources:
  App\Entity\Studio:
    shortName: 'Studio'
    description: 'Studio produkcji'
    denormalizationContext:
      groups: [ 'studioWrite' ]
    operations:
      ApiPlatform\Metadata\GetCollection:
        normalizationContext:
          groups: [ 'studioCollection' ]
      ApiPlatform\Metadata\Get:
        normalizationContext:
          groups: [ 'studioGet' ]
      ApiPlatform\Metadata\Post: ~
      ApiPlatform\Metadata\Patch: ~
      ApiPlatform\Metadata\Delete: ~

