resources:
  App\Entity\User:
    shortName: 'User'
    description: 'Użytkownik'
    normalizationContext:
      groups: ['user']
    operations:
      ApiPlatform\Metadata\GetCollection:
        uriTemplate: /allUsers
        filters: ['users.search_filter', 'users.order_filter']
      ApiPlatform\Metadata\Get: ~
      ApiPlatform\Metadata\Post:
        denormalizationContext:
          groups: [ 'userCreate' ]
        processor: App\State\UserStateProcessor
      ApiPlatform\Metadata\Patch: ~
      ApiPlatform\Metadata\Delete: ~
      set_role:
        uriTemplate: /setRole/{uuid}
        class: ApiPlatform\Metadata\Patch
        method: [PATCH]
        groups: ['setRole']

properties:
  App\Entity\User:
    id:
      identifier: false
    uuid:
      identifier: true
